#!/bin/bash

# prepare working folder
rm -rf build
mkdir -p build
cp -r Thonny.app.template build
mv build/Thonny.app.template build/Thonny.app
cp -r ../src/* build/Thonny.app/Contents/MacOS
chmod 755 build/Thonny.app/Contents/MacOS/thonny
rm -rf build/Thonny.app/Contents/MacOs/__pycache__
rm -rf build/Thonny.app/Contents/MacOs/*.pyo
rm -rf build/Thonny.app/Contents/MacOs/*.pyc 

# get and set version
VERSION=$(<../src/VERSION)
sed -i.bak "s/VERSION/$VERSION/" build/Thonny.app/Contents/Info.plist


# create dmg
FILENAME=Thonny-$VERSION.dmg
rm -f $FILENAME
hdiutil create -srcfolder build/Thonny.app $FILENAME
hdiutil internet-enable -yes $FILENAME

