# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: exa/diff_action_pb/diff_action.proto
# Protobuf Python Version: 5.27.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    3,
    '',
    'exa/diff_action_pb/diff_action.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from exa.codeium_common_pb import codeium_common_pb2 as exa_dot_codeium__common__pb_dot_codeium__common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n$exa/diff_action_pb/diff_action.proto\x12\x12\x65xa.diff_action_pb\x1a*exa/codeium_common_pb/codeium_common.proto\"\xb8\x01\n\x0bUnifiedDiff\x12\x45\n\x05lines\x18\x03 \x03(\x0b\x32/.exa.diff_action_pb.UnifiedDiff.UnifiedDiffLineR\x05lines\x1a\x62\n\x0fUnifiedDiffLine\x12\x12\n\x04text\x18\x01 \x01(\tR\x04text\x12;\n\x04type\x18\x02 \x01(\x0e\x32\'.exa.diff_action_pb.UnifiedDiffLineTypeR\x04type\"\x91\x02\n\tDiffBlock\x12\x1d\n\nstart_line\x18\x01 \x01(\x05R\tstartLine\x12\x19\n\x08\x65nd_line\x18\x02 \x01(\x05R\x07\x65ndLine\x12\x42\n\x0cunified_diff\x18\x03 \x01(\x0b\x32\x1f.exa.diff_action_pb.UnifiedDiffR\x0bunifiedDiff\x12\x44\n\rfrom_language\x18\x04 \x01(\x0e\x32\x1f.exa.codeium_common_pb.LanguageR\x0c\x66romLanguage\x12@\n\x0bto_language\x18\x05 \x01(\x0e\x32\x1f.exa.codeium_common_pb.LanguageR\ntoLanguage*\xa9\x01\n\x13UnifiedDiffLineType\x12&\n\"UNIFIED_DIFF_LINE_TYPE_UNSPECIFIED\x10\x00\x12!\n\x1dUNIFIED_DIFF_LINE_TYPE_INSERT\x10\x01\x12!\n\x1dUNIFIED_DIFF_LINE_TYPE_DELETE\x10\x02\x12$\n UNIFIED_DIFF_LINE_TYPE_UNCHANGED\x10\x03\x42\xc1\x01\n\x16\x63om.exa.diff_action_pbB\x0f\x44iffActionProtoP\x01Z5github.com/Exafunction/Exafunction/exa/diff_action_pb\xa2\x02\x03\x45\x44X\xaa\x02\x10\x45xa.DiffActionPb\xca\x02\x10\x45xa\\DiffActionPb\xe2\x02\x1c\x45xa\\DiffActionPb\\GPBMetadata\xea\x02\x11\x45xa::DiffActionPbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'exa.diff_action_pb.diff_action_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\026com.exa.diff_action_pbB\017DiffActionProtoP\001Z5github.com/Exafunction/Exafunction/exa/diff_action_pb\242\002\003EDX\252\002\020Exa.DiffActionPb\312\002\020Exa\\DiffActionPb\342\002\034Exa\\DiffActionPb\\GPBMetadata\352\002\021Exa::DiffActionPb'
  _globals['_UNIFIEDDIFFLINETYPE']._serialized_start=568
  _globals['_UNIFIEDDIFFLINETYPE']._serialized_end=737
  _globals['_UNIFIEDDIFF']._serialized_start=105
  _globals['_UNIFIEDDIFF']._serialized_end=289
  _globals['_UNIFIEDDIFF_UNIFIEDDIFFLINE']._serialized_start=191
  _globals['_UNIFIEDDIFF_UNIFIEDDIFFLINE']._serialized_end=289
  _globals['_DIFFBLOCK']._serialized_start=292
  _globals['_DIFFBLOCK']._serialized_end=565
# @@protoc_insertion_point(module_scope)
