# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from exa.language_server_pb import language_server_pb2 as exa_dot_language__server__pb_dot_language__server__pb2


class LanguageServerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetCompletions = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/GetCompletions',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetCompletionsRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetCompletionsResponse.FromString,
                _registered_method=True)
        self.AcceptCompletion = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/AcceptCompletion',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.AcceptCompletionRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.AcceptCompletionResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/Heartbeat',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.GetAuthToken = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/GetAuthToken',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetAuthTokenRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetAuthTokenResponse.FromString,
                _registered_method=True)
        self.RecordEvent = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/RecordEvent',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordEventRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordEventResponse.FromString,
                _registered_method=True)
        self.CancelRequest = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/CancelRequest',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.CancelRequestRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.CancelRequestResponse.FromString,
                _registered_method=True)
        self.Exit = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/Exit',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.ExitRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.ExitResponse.FromString,
                _registered_method=True)
        self.GetProcesses = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/GetProcesses',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetProcessesRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetProcessesResponse.FromString,
                _registered_method=True)
        self.GetChatMessage = channel.unary_stream(
                '/exa.language_server_pb.LanguageServerService/GetChatMessage',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetChatMessageRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetChatMessageResponse.FromString,
                _registered_method=True)
        self.RecordChatFeedback = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/RecordChatFeedback',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatFeedbackRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatFeedbackResponse.FromString,
                _registered_method=True)
        self.RecordChatPanelSession = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/RecordChatPanelSession',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatPanelSessionRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatPanelSessionResponse.FromString,
                _registered_method=True)
        self.ClusteredSearch = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/ClusteredSearch',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.ClusteredSearchRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.ClusteredSearchResponse.FromString,
                _registered_method=True)
        self.ExactSearch = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/ExactSearch',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.ExactSearchRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.ExactSearchResponse.FromString,
                _registered_method=True)
        self.AddTrackedWorkspace = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/AddTrackedWorkspace',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.AddTrackedWorkspaceRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.AddTrackedWorkspaceResponse.FromString,
                _registered_method=True)
        self.RemoveTrackedWorkspace = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/RemoveTrackedWorkspace',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RemoveTrackedWorkspaceRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RemoveTrackedWorkspaceResponse.FromString,
                _registered_method=True)
        self.RefreshContextForIdeAction = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/RefreshContextForIdeAction',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RefreshContextForIdeActionRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RefreshContextForIdeActionResponse.FromString,
                _registered_method=True)
        self.GetFunctions = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/GetFunctions',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetFunctionsRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetFunctionsResponse.FromString,
                _registered_method=True)
        self.GetUserStatus = channel.unary_unary(
                '/exa.language_server_pb.LanguageServerService/GetUserStatus',
                request_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetUserStatusRequest.SerializeToString,
                response_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetUserStatusResponse.FromString,
                _registered_method=True)


class LanguageServerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetCompletions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AcceptCompletion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAuthToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordEvent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProcesses(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChatMessage(self, request, context):
        """Chat RPCs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordChatFeedback(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RecordChatPanelSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClusteredSearch(self, request, context):
        """Search RPCs.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExactSearch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddTrackedWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveTrackedWorkspace(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshContextForIdeAction(self, request, context):
        """Refresh context with editor state on IDE events happening.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetFunctions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LanguageServerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetCompletions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCompletions,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetCompletionsRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetCompletionsResponse.SerializeToString,
            ),
            'AcceptCompletion': grpc.unary_unary_rpc_method_handler(
                    servicer.AcceptCompletion,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.AcceptCompletionRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.AcceptCompletionResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.HeartbeatRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.HeartbeatResponse.SerializeToString,
            ),
            'GetAuthToken': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAuthToken,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetAuthTokenRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetAuthTokenResponse.SerializeToString,
            ),
            'RecordEvent': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordEvent,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordEventRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordEventResponse.SerializeToString,
            ),
            'CancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRequest,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.CancelRequestRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.CancelRequestResponse.SerializeToString,
            ),
            'Exit': grpc.unary_unary_rpc_method_handler(
                    servicer.Exit,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.ExitRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.ExitResponse.SerializeToString,
            ),
            'GetProcesses': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProcesses,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetProcessesRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetProcessesResponse.SerializeToString,
            ),
            'GetChatMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.GetChatMessage,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetChatMessageRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetChatMessageResponse.SerializeToString,
            ),
            'RecordChatFeedback': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordChatFeedback,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatFeedbackRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatFeedbackResponse.SerializeToString,
            ),
            'RecordChatPanelSession': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordChatPanelSession,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatPanelSessionRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RecordChatPanelSessionResponse.SerializeToString,
            ),
            'ClusteredSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ClusteredSearch,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.ClusteredSearchRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.ClusteredSearchResponse.SerializeToString,
            ),
            'ExactSearch': grpc.unary_unary_rpc_method_handler(
                    servicer.ExactSearch,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.ExactSearchRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.ExactSearchResponse.SerializeToString,
            ),
            'AddTrackedWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.AddTrackedWorkspace,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.AddTrackedWorkspaceRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.AddTrackedWorkspaceResponse.SerializeToString,
            ),
            'RemoveTrackedWorkspace': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveTrackedWorkspace,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RemoveTrackedWorkspaceRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RemoveTrackedWorkspaceResponse.SerializeToString,
            ),
            'RefreshContextForIdeAction': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshContextForIdeAction,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.RefreshContextForIdeActionRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.RefreshContextForIdeActionResponse.SerializeToString,
            ),
            'GetFunctions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetFunctions,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetFunctionsRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetFunctionsResponse.SerializeToString,
            ),
            'GetUserStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserStatus,
                    request_deserializer=exa_dot_language__server__pb_dot_language__server__pb2.GetUserStatusRequest.FromString,
                    response_serializer=exa_dot_language__server__pb_dot_language__server__pb2.GetUserStatusResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'exa.language_server_pb.LanguageServerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('exa.language_server_pb.LanguageServerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LanguageServerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetCompletions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/GetCompletions',
            exa_dot_language__server__pb_dot_language__server__pb2.GetCompletionsRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.GetCompletionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AcceptCompletion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/AcceptCompletion',
            exa_dot_language__server__pb_dot_language__server__pb2.AcceptCompletionRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.AcceptCompletionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/Heartbeat',
            exa_dot_language__server__pb_dot_language__server__pb2.HeartbeatRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetAuthToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/GetAuthToken',
            exa_dot_language__server__pb_dot_language__server__pb2.GetAuthTokenRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.GetAuthTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordEvent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/RecordEvent',
            exa_dot_language__server__pb_dot_language__server__pb2.RecordEventRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.RecordEventResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/CancelRequest',
            exa_dot_language__server__pb_dot_language__server__pb2.CancelRequestRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.CancelRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/Exit',
            exa_dot_language__server__pb_dot_language__server__pb2.ExitRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.ExitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProcesses(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/GetProcesses',
            exa_dot_language__server__pb_dot_language__server__pb2.GetProcessesRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.GetProcessesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChatMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/GetChatMessage',
            exa_dot_language__server__pb_dot_language__server__pb2.GetChatMessageRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.GetChatMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordChatFeedback(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/RecordChatFeedback',
            exa_dot_language__server__pb_dot_language__server__pb2.RecordChatFeedbackRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.RecordChatFeedbackResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RecordChatPanelSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/RecordChatPanelSession',
            exa_dot_language__server__pb_dot_language__server__pb2.RecordChatPanelSessionRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.RecordChatPanelSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClusteredSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/ClusteredSearch',
            exa_dot_language__server__pb_dot_language__server__pb2.ClusteredSearchRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.ClusteredSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExactSearch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/ExactSearch',
            exa_dot_language__server__pb_dot_language__server__pb2.ExactSearchRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.ExactSearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddTrackedWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/AddTrackedWorkspace',
            exa_dot_language__server__pb_dot_language__server__pb2.AddTrackedWorkspaceRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.AddTrackedWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveTrackedWorkspace(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/RemoveTrackedWorkspace',
            exa_dot_language__server__pb_dot_language__server__pb2.RemoveTrackedWorkspaceRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.RemoveTrackedWorkspaceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshContextForIdeAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/RefreshContextForIdeAction',
            exa_dot_language__server__pb_dot_language__server__pb2.RefreshContextForIdeActionRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.RefreshContextForIdeActionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetFunctions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/GetFunctions',
            exa_dot_language__server__pb_dot_language__server__pb2.GetFunctionsRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.GetFunctionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/exa.language_server_pb.LanguageServerService/GetUserStatus',
            exa_dot_language__server__pb_dot_language__server__pb2.GetUserStatusRequest.SerializeToString,
            exa_dot_language__server__pb_dot_language__server__pb2.GetUserStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
