"""
Module: 'samd' on micropython-v1.25.0-samd-SEEED_WIO_TERMINAL
"""

# MCU: {'version': '1.25.0', 'mpy': 'v6.3', 'port': 'samd', 'board': 'SEEED_WIO_TERMINAL', 'family': 'micropython', 'build': '', 'arch': 'armv7emsp', 'ver': '1.25.0', 'cpu': 'SAMD51P19A'}
# Stubber: v1.24.0
from __future__ import annotations
from _typeshed import Incomplete

def pininfo(*args, **kwargs) -> Incomplete: ...

class Flash:
    def readblocks(self, *args, **kwargs) -> Incomplete: ...
    def writeblocks(self, *args, **kwargs) -> Incomplete: ...
    def ioctl(self, *args, **kwargs) -> Incomplete: ...
    def __init__(self, *argv, **kwargs) -> None: ...
