#!/bin/bash

ugly_macos_dir="$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
contents_dir="$(cd "${ugly_macos_dir}/.." && pwd -P)"
macos_dir="$contents_dir/MacOS"
res_dir="$contents_dir/Resources"
bin_dir="$contents_dir/Frameworks/Python.framework/Versions/3.7/bin"
executable="$macos_dir/Python"

export SSL_CERT_DIR="$contents_dir/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/certifi"
export SSL_CERT_FILE="$SSL_CERT_DIR/cacert.pem"

unset PYTHONHOME
unset PYTHONPATH
unset PYTHONSTARTUP
unset PYTHONINSPECT

export TCL_LIBRARY="$contents_dir/Frameworks/Python.framework/Versions/3.7/lib/tcl8.6"
export TK_LIBRARY="$contents_dir/Frameworks/Python.framework/Versions/3.7/lib/tk8.6"

export PYTHON_SYS_EXECUTABLE="$executable"

exec "$executable" -E "$res_dir/thonnymain.py" "$@"

