#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export LD_LIBRARY_PATH=$DIR/../lib
export SSL_CERT_FILE=$(readlink -m $DIR/../lib/python3.6/site-packages/certifi/cacert.pem)
export SSL_CERT_DIR=$(readlink -m $DIR/../lib/python3.6/site-packages/certifi)

$DIR/python3.6 -m thonny "$@"
