#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export LD_LIBRARY_PATH=$DIR/../lib
export SSL_CERT_DIR=$(readlink -m $DIR/../lib/python3.6/site-packages/certifi)
export SSL_CERT_FILE="$SSL_CERT_DIR/cacert.pem"

$DIR/python3.6 -m thonny "$@"
