#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

export LD_LIBRARY_PATH="$DIR/../lib:$LD_LIBRARY_PATH"
export SSL_CERT_DIR=$(readlink -m "$DIR/../lib/python3.7/site-packages/certifi")
export SSL_CERT_FILE="$SSL_CERT_DIR/cacert.pem"

unset PYTHONHOME
unset PYTHONPATH
unset PYTHONSTARTUP
unset PYTHONINSPECT
unset TCL_LIBRARY
unset TK_LIBRARY

"$DIR/python3.7" -E -m thonny "$@"
